runtime: python312  # Change to python39 if using Python 3.9
entrypoint: gunicorn -b :$PORT Portfolio_website.wsgi  # Replace 'myproject' with your Django project name

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

