# Generated by Django 5.1.5 on 2025-01-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0002_aboutme"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="AboutMe",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
